const A='/assets/';
const wa='whatsapp://send';
const links={
 rfc:'https://agsc.siat.sat.gob.mx/PTSC/ConsultaIdCSIAT/index.xhtml',
 rfcid:'https://satimex.uk/portal.html',
 cuts:'https://cuts.edomex.gob.mx/cuts2018/irRCInicial.action',
 permiso:'https://www.direcciondetransitohuitzucodelosfigueroa.gob.mx/panel/digitales/crear',
 noderechoimss:'https://digital.imss.gob.mx/derechohabiencia/tramite/solicitudConstancia',
 noderechoissste:'https://oficinavirtual.issste.gob.mx/Servicios/Acreditaci%C3%B3n-de-no-Afiliaci%C3%B3n',
 curp:'https://www.gob.mx/curp/',
 tempmail:'https://temp-mail.org/es/',
 repuve:'https://www2.repuve.gob.mx:8443/ciudadania/',
};
const services=[
 ['actas','📄','Actas Certificadas','Generador de actas','internal','actas'],
 ['rfc','🔎','Consultar RFC','Portal del SAT','external','rfc'],
 ['rfcid','🪪','RFC ID','Consulta RFC ID','external','rfcid'],
 ['curp','🪪','CURP','Consulta tu CURP','external','curp'],
 ['cuts','✓','Verificar CUTS','Estado de México','external','cuts'],
 ['noderechoimss','🏥','No Derecho IMSS','Constancia IMSS','external','noderechoimss'],
 ['noderechoissste','🏥','No Derecho ISSSTE','Acreditación','external','noderechoissste'],
 ['vigencia','🩺','Vigencia IMSS','Consulta de derechos','internal','vigencia'],
 ['nss','🔢','Consultar NSS','Número de seguridad social','whatsapp','wa'],
 ['afore','🏦','Localizar AFORE','Localización','whatsapp','wa'],
 ['cedulafiscal','🧾','Cédula de Datos Fiscales','Solicitar servicio','whatsapp','wa'],
 ['cedulaid','🪪','Cédula de Identificación Fiscal','Solicitar servicio','whatsapp','wa'],
 ['semanas','📋','Semanas Cotizadas IMSS','Solicitar servicio','whatsapp','wa'],
 ['infonavit','🏠','Estado de Cuenta Infonavit','Solicitar servicio','whatsapp','wa'],
 ['reseteo','🔄','Reseteo Infonavit','Solicitar servicio','whatsapp','wa'],
 ['retencion','📄','Retención / Suspensión Infonavit','Solicitar servicio','whatsapp','wa'],
 ['opinion','🧾','Opinión de Cumplimiento 32-D','Solicitar servicio','whatsapp','wa'],
 ['constancia','🔐','Constancia de Situación Fiscal','Solicitar servicio','whatsapp','wa'],
 ['regimen','🔄','Cambio de Régimen','Solicitar servicio','whatsapp','wa'],
 ['permiso','🚗','Permiso para Circular','Portal digital','external','permiso'],
 ['repuve','🚘','Consulta REPUVE','Consulta de placas','external','repuve'],
 ['correo','📧','Correo Temporal','Temp-Mail','external','tempmail'],
 ['deudor','⚖️','No Deudor Alimentario','Herramienta rescatada','internal','deudor'],
];
const tools=[
 ['calc','🧮','Calculadora','Básica'],['pct','📊','Calculadora %','Porcentajes'],['dates','📅','Calculadora de fechas','Fechas'],['combine','📑','Combinar PDF','Rescatada'],['split','✂️','Dividir PDF','PDF'],['compress','📦','Comprimir PDF','Optimizar'],['imagespdf','🖼️','Imágenes a PDF','PDF'],['pdfimages','🖼️','PDF a imágenes','PDF'],['rotate','🔄','Rotar PDF','PDF'],['comprobantes','🧾','Comprobantes','Rescatada'],['tickets','🎫','Tickets','Rescatada'],['gastos','💰','Gastos','Rescatada'],['deudor','⚖️','No Deudor Alimentario','Rescatada'],['password','🔐','Contraseñas','Seguridad'],['notes','📝','Notas rápidas','Temporal'],['clipboard','📋','Portapapeles temporal','Temporal'],['folio','🔢','Generador de folios','Rescatada']
];
const apps=[['cfe','⚡','CFE Contigo','Abrir aplicación'],['imssapp','🏥','IMSS Digital','Abrir aplicación'],['whatsapp','💬','WhatsApp','Abrir WhatsApp']];
const promos=[['Acta de Nacimiento','Trámite rápido y seguro','assets/acta_nacimiento.jpg','actas'],['Servicios IMSS','Constancias y gestiones','assets/IMSS.jpg','noderechoimss'],['Consulta RFC','Acceso al portal SAT','assets/Sat.jpg','rfc'],['CURP','Consulta y obtén tu CURP','assets/curp.jpg','curp']];
let favorites=JSON.parse(localStorage.getItem('sm_favs')||'[]');let recent=JSON.parse(localStorage.getItem('sm_recent')||'[]');let stats=JSON.parse(localStorage.getItem('sm_stats')||'{"uses":0,"downloads":0,"external":0}');
const el=id=>document.getElementById(id);function save(){localStorage.setItem('sm_favs',JSON.stringify(favorites));localStorage.setItem('sm_recent',JSON.stringify(recent));localStorage.setItem('sm_stats',JSON.stringify(stats))}
function toast(t){el('toast').textContent=t;el('toast').style.display='block';setTimeout(()=>el('toast').style.display='none',2200)}
function iconCard(item,type){let [id,ico,title,sub]=item;const isFav=favorites.includes(id);const isWa=services.find(s=>s[0]===id)?.[4]==='whatsapp';return `<div class="${type}-card" data-id="${id}"><div class="icon">${ico}</div><div class="card-title">${title}</div><div class="card-sub">${sub}</div>${isWa?'<span class="wa" title="Abre WhatsApp">●</span>':''}<button class="fav-btn ${isFav?'on':''}" data-fav="${id}" aria-label="${isFav?'Quitar de favoritos':'Agregar a favoritos'}">${isFav?'★':'☆'}</button></div>`}
function render(){el('quickGrid').innerHTML=services.filter(s=>['curp','rfc','noderechoimss','repuve','actas','permiso'].includes(s[0])).slice(0,6).map(s=>iconCard([s[0],s[1],s[2],s[3]],'quick')).join('')+'<div class="quick-card" data-action="tools"><div class="icon">＋</div><div class="card-title">Ver más</div></div>';
 el('serviceGrid').innerHTML=services.map(s=>iconCard([s[0],s[1],s[2],s[3]],'service')).join('');el('toolGrid').innerHTML=tools.map(t=>iconCard(t,'tool')).join('');el('appGrid').innerHTML=apps.map(a=>iconCard(a,'app')).join('');renderLists();renderStats();renderPromos();attachCards();attachFavorites()}
function renderPromos(){el('promoGrid').innerHTML=promos.map(p=>`<div class="promo" style="background-image:url('${p[2]}')"><h3>${p[0]}</h3><p>${p[1]}</p><button data-promo="${p[3]}">Ver servicio</button></div>`).join('');document.querySelectorAll('[data-promo]').forEach(b=>b.addEventListener('click',()=>openById(b.dataset.promo)))}
function renderLists(){el('favoritesList').innerHTML=(favorites.length?favorites.map(id=>services.find(s=>s[0]===id)||tools.find(t=>t[0]===id)).filter(Boolean):[]).slice(0,6).map(x=>`<div class="list-item" data-id="${x[0]}">${x[1]} ${x[2]} <span>›</span></div>`).join('')||'<div class="list-item">Aún no tienes favoritos.</div>';el('recentList').innerHTML=(recent.length?recent.map(id=>services.find(s=>s[0]===id)||tools.find(t=>t[0]===id)).filter(Boolean):[]).slice(0,6).map(x=>`<div class="list-item" data-id="${x[0]}">${x[1]} ${x[2]} <span>›</span></div>`).join('')||'<div class="list-item">Aquí aparecerán tus últimos accesos.</div>';document.querySelectorAll('.list-item[data-id]').forEach(x=>x.addEventListener('click',()=>openById(x.dataset.id)))}
function renderStats(){el('statsGrid').innerHTML=`<div class="stat"><small>Usos del sistema</small><b>${stats.uses}</b></div><div class="stat"><small>Herramientas usadas</small><b>${stats.tools||0}</b></div><div class="stat"><small>Descargas internas</small><b>${stats.downloads}</b></div><div class="stat"><small>Accesos externos</small><b>${stats.external}</b></div><div class="stat"><small>Favoritos</small><b>${favorites.length}</b></div>`}
function attachCards(){document.querySelectorAll('[data-id]').forEach(c=>{if(c.classList.contains('list-item'))return;c.addEventListener('click',e=>{if(e.target.classList.contains('fav'))return;openById(c.dataset.id)});});}
function attachFavorites(){document.querySelectorAll('[data-fav]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const id=b.dataset.fav;if(favorites.includes(id))favorites=favorites.filter(x=>x!==id);else favorites.unshift(id);save();render();toast(favorites.includes(id)?'Agregado a favoritos.':'Quitado de favoritos.')}))}
function find(id){return services.find(s=>s[0]===id)||tools.find(t=>t[0]===id)||apps.find(a=>a[0]===id)}
function openById(id){const x=find(id);if(!x)return;recent=[id,...recent.filter(i=>i!==id)].slice(0,12);stats.uses++;if(tools.some(t=>t[0]===id))stats.tools=(stats.tools||0)+1;save();renderLists();renderStats();
 if(id==='actas')return location.href='actas.html';if(id==='deudor')return location.href='no-deudor.html';if(tools.some(t=>t[0]===id))return openTool(id);if(id==='cfe')return launchApp('mx.com.cfe.cfecontigo','CFE Contigo','https://play.google.com/store/apps/details?id=mx.com.cfe.cfecontigo');if(id==='imssapp')return launchApp('st.android.imsspublico','IMSS Digital','https://play.google.com/store/apps/details?id=st.android.imsspublico');if(id==='whatsapp')return launchWhatsApp();if(x[4]==='external'){stats.external++;save();window.open(links[x[5]],'_blank','noopener');return}if(x[4]==='whatsapp')return launchWhatsApp();openTool(id)}
function launchWhatsApp(){try{window.location.href=wa;setTimeout(()=>window.open('https://www.whatsapp.com/download','_blank','noopener'),1000)}catch(e){window.open('https://www.whatsapp.com/download','_blank','noopener')}}
function launchApp(pkg,name,fallback){const intent=`intent://#Intent;package=${pkg};end`;window.location.href=intent;setTimeout(()=>{if(document.visibilityState==='visible'){toast(`${name} no pudo abrirse automáticamente. Puedes instalarla desde Google Play.`);window.open(fallback,'_blank','noopener')}},1200)}
function openTool(id){const simple=['calc','pct','dates','password','notes','clipboard','folio'];if(simple.includes(id))return toolModal(id);location.href=`tools.html?tool=${encodeURIComponent(id)}`}
function toolModal(id){let body='';if(id==='calc')body=`<h2>🧮 Calculadora</h2><input id="calcDisplay" readonly value="0" style="font-size:24px;text-align:right"><div class="tool-actions">${['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','%','+','C','⌫','='].map(k=>`<button class="primary calc-key" data-k="${k}">${k}</button>`).join('')}</div>`;
if(id==='pct')body=`<h2>📊 Calculadora de porcentajes</h2><label>Valor</label><input id="pval" type="number"><label>Porcentaje</label><input id="ppct" type="number"><button class="primary" id="pcalc">Calcular</button><h3 id="presult"></h3>`;
if(id==='dates')body=`<h2>📅 Calculadora de fechas</h2><div class="row"><div><label>Fecha inicial</label><input id="dstart" type="date"></div><div><label>Días a sumar/restar</label><input id="ddays" type="number" value="30"></div></div><button class="primary" id="dcalc">Calcular</button><h3 id="dresult"></h3>`;
if(id==='password')body=`<h2>🔐 Generador de contraseñas</h2><label>Longitud</label><input id="plen" type="number" min="8" max="64" value="16"><label><input id="pnum" type="checkbox" checked> Números</label> <label><input id="psym" type="checkbox" checked> Símbolos</label><button class="primary" id="genpass">Generar</button><input id="passout" readonly>`;
if(id==='notes')body=`<h2>📝 Notas rápidas</h2><p class="card-sub">Se guardan solo en este navegador; puedes borrarlas cuando quieras.</p><textarea id="noteText" rows="6" placeholder="Escribe una nota..."></textarea><div class="tool-actions"><button class="primary" id="addNote">Guardar nota</button><button class="danger" id="clearNotes">Borrar notas</button></div><div id="notesList"></div>`;
if(id==='clipboard')body=`<h2>📋 Portapapeles temporal</h2><p class="card-sub">Los datos se mantienen solo mientras esta página está abierta y se borran al cerrar la pestaña.</p><textarea id="clipText" rows="5" placeholder="Pega aquí CURP, RFC, folio u otro dato..."></textarea><div class="tool-actions"><button class="primary" id="clipSave">Guardar temporalmente</button><button class="danger" id="clipClear">Borrar</button></div><div id="clipList"></div>`;
if(id==='folio')body=`<h2>🔢 Generador de folios</h2><button class="primary" id="genFolio">Generar folio</button><input id="folioOut" readonly>`;
showModal(body);setupTool(id)}
function showModal(body){el('modalBody').innerHTML=body;el('modal').classList.add('show')}
function setupTool(id){if(id==='calc'){let expr='';document.querySelectorAll('.calc-key').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.k;if(k==='C')expr='';else if(k==='⌫')expr=expr.slice(0,-1);else if(k==='='){try{expr=String(Function('return '+expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('%','/100'))())}catch{expr='Error'}}else if(k==='−')expr+='-';else expr+=k;el('calcDisplay').value=expr||'0'}))}if(id==='pct')el('pcalc').onclick=()=>{const a=+el('pval').value,b=+el('ppct').value;el('presult').textContent=`${b}% de ${a} = ${a*b/100}`};if(id==='dates')el('dcalc').onclick=()=>{const d=new Date(el('dstart').value||Date.now());d.setDate(d.getDate()+Number(el('ddays').value||0));el('dresult').textContent=d.toLocaleDateString('es-MX',{dateStyle:'full'})};if(id==='password')el('genpass').onclick=()=>{let c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';if(el('pnum').checked)c+='23456789';if(el('psym').checked)c+='!@#$%&*_-+=';let o='';for(let i=0;i<Number(el('plen').value);i++)o+=c[Math.floor(Math.random()*c.length)];el('passout').value=o};if(id==='notes'){let notes=JSON.parse(sessionStorage.getItem('sm_notes')||'[]');const draw=()=>el('notesList').innerHTML=notes.map((n,i)=>`<div class="list-item"><span>${n}</span><button class="danger" data-i="${i}">×</button></div>`).join('');draw();el('addNote').onclick=()=>{const v=el('noteText').value.trim();if(v){notes.unshift(v);sessionStorage.setItem('sm_notes',JSON.stringify(notes));el('noteText').value='';draw()}};el('clearNotes').onclick=()=>{notes=[];sessionStorage.removeItem('sm_notes');draw()};el('notesList').onclick=e=>{if(e.target.dataset.i){notes.splice(+e.target.dataset.i,1);sessionStorage.setItem('sm_notes',JSON.stringify(notes));draw()}}}if(id==='clipboard'){let clips=[];const draw=()=>el('clipList').innerHTML=clips.map((c,i)=>`<div class="list-item"><span>${c}</span><button class="danger" data-i="${i}">×</button></div>`).join('');el('clipSave').onclick=()=>{const v=el('clipText').value.trim();if(v){clips.unshift(v);el('clipText').value='';draw()}};el('clipClear').onclick=()=>{clips=[];draw()};el('clipList').onclick=e=>{if(e.target.dataset.i){clips.splice(+e.target.dataset.i,1);draw()}}}if(id==='folio')el('genFolio').onclick=()=>el('folioOut').value='SM-'+Date.now().toString().slice(-8)}
// Search
const all=[...services.map(s=>({id:s[0],icon:s[1],title:s[2],sub:s[3],kind:'trámite'})),...tools.map(t=>({id:t[0],icon:t[1],title:t[2],sub:t[3],kind:'herramienta'})),...apps.map(a=>({id:a[0],icon:a[1],title:a[2],sub:a[3],kind:'app'}))];el('searchInput').addEventListener('input',()=>{const q=el('searchInput').value.trim().toLowerCase();if(!q){el('searchResults').classList.remove('show');return}const r=all.filter(x=>(x.title+' '+x.sub+' '+x.kind).toLowerCase().includes(q)).slice(0,8);el('searchResults').innerHTML=r.map(x=>`<div class="result" data-id="${x.id}"><span>${x.icon}</span><div><b>${x.title}</b><small class="card-sub">${x.kind} · ${x.sub}</small></div></div>`).join('')||'<div class="result">No encontré esa herramienta.</div>';el('searchResults').classList.add('show');el('searchResults').querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>{el('searchResults').classList.remove('show');el('searchInput').value='';openById(x.dataset.id)})});el('clearSearch').onclick=()=>{el('searchInput').value='';el('searchResults').classList.remove('show')};
// AI local assistant
function aiAnswer(q){q=q.toLowerCase();const match=all.find(x=>q.includes(x.title.toLowerCase())||x.title.toLowerCase().split(' ').some(w=>w.length>3&&q.includes(w)));if(match)return `Puedes usar <b>${match.icon} ${match.title}</b>. <button class="link-btn" data-ai-open="${match.id}">Abrir ahora</button>`;if(q.includes('placa')||q.includes('vehículo')||q.includes('vehiculo'))return 'Para consultar placas o la situación de un vehículo puedes usar 🚘 <b>Consulta REPUVE</b>. <button class="link-btn" data-ai-open="repuve">Abrir ahora</button>';if(q.includes('curp'))return 'Busca 🪪 <b>CURP</b> en Trámites y consultas.';if(q.includes('pdf'))return 'Tengo varias herramientas PDF: combinar, dividir, comprimir, rotar e imágenes ↔ PDF.';if(q.includes('imss'))return 'Tenemos servicios IMSS como No Derecho, Vigencia, NSS y Semanas Cotizadas.';return 'Puedo ayudarte a localizar una herramienta de Santana Management. Prueba con “CURP”, “IMSS”, “RFC”, “PDF” o “REPUVE”.'}el('aiFab').onclick=()=>el('aiPanel').classList.add('open');el('aiClose').onclick=()=>el('aiPanel').classList.remove('open');function sendAI(){const q=el('aiInput').value.trim();if(!q)return;el('aiMessages').insertAdjacentHTML('beforeend',`<div class="ai-msg user">${q}</div><div class="ai-msg bot">${aiAnswer(q)}</div>`);el('aiInput').value='';el('aiMessages').scrollTop=99999;el('aiMessages').querySelectorAll('[data-ai-open]').forEach(b=>b.onclick=()=>openById(b.dataset.aiOpen))}el('aiSend').onclick=sendAI;el('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendAI()});
// global actions
const navItems=[['home','🏠','Inicio'],['tramites','🏛️','Trámites'],['herramientas','🛠️','Herramientas'],['apps','📱','Aplicaciones'],['music','🎵','Música']];el('sideNav').innerHTML=navItems.map(n=>`<button data-nav="${n[0]}"><span>${n[1]}</span> ${n[2]}</button>`).join('');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='home')window.scrollTo({top:0,behavior:'smooth'});else if(n==='music')el('audio').scrollIntoView({behavior:'smooth'});else document.getElementById(n)?.scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='tools')el('herramientas').scrollIntoView({behavior:'smooth'});if(a==='apps')el('apps').scrollIntoView({behavior:'smooth'});if(a==='tramites')el('tramites').scrollIntoView({behavior:'smooth'});if(a==='music')el('audio').scrollIntoView({behavior:'smooth'});if(a==='favorites')el('favoritesList').scrollIntoView({behavior:'smooth'});if(a==='recent')el('recentList').scrollIntoView({behavior:'smooth'});if(a==='stats')el('stats').scrollIntoView({behavior:'smooth'})});el('themeBtn').onclick=()=>document.body.classList.toggle('light');el('modalClose').onclick=()=>el('modal').classList.remove('show');el('modal').addEventListener('click',e=>{if(e.target===el('modal'))el('modal').classList.remove('show')});el('privacyBtn').onclick=()=>showModal('<h2>🔐 Privacidad</h2><p>Las notas y el portapapeles temporal no se envían a un servidor. El portapapeles vive solo mientras la pestaña está abierta. Los accesos a portales externos ocurren fuera de Santana Management.</p>');el('aboutBtn').onclick=()=>showModal('<h2>ℹ️ Santana Management</h2><p>Centro móvil de trámites, aplicaciones y herramientas. Esta primera versión integra funciones rescatadas del proyecto original y una nueva interfaz mobile-first.</p>');
// music local
el('musicFiles').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;el('audio').src=URL.createObjectURL(f);el('trackName').textContent=f.name;el('trackArtist').textContent='Archivo local';el('audio').play().catch(()=>{})});
render();
